.pragma library
.import "FilterChainGen.js" as FilterChainGen

// Renders a per-channel cava(1) config for the EQ view's live background
// spectrum. Source is the channel's own capture-side virtual sink's
// pulse-compat monitor (`waveform_<id>.monitor`) — the *pre*-EQ signal, i.e.
// what's arriving on the channel, not what the filter chain outputs. This
// isn't a compromise: the channel's post-EQ node (`<id>_output`) is a plain
// playback stream, not a sink (see FilterChainGen.js's `playback.props` —
// no `media.class` set there), so it has no monitor source cava could
// target at all without restructuring the filter graph to add an
// intermediate sink purely for this cosmetic purpose. Showing the incoming
// signal is also the conventional choice for an EQ analyzer overlay (same
// as most parametric EQ plugins default to) — the live curve on top is what
// reflects the user's shaping, not the spectrum fill underneath it.
function monitorSource(channelId) {
  return FilterChainGen.sinkNodeName(channelId) + ".monitor"
}

function renderConfig(channelId, barCount) {
  var lines = [
    "; Generated by the Waveform plugin — do not edit by hand.",
    "",
    "[general]",
    "bars = " + barCount,
    "framerate = 30",
    "",
    "[input]",
    "method = pulse",
    "source = " + monitorSource(channelId),
    "",
    "[output]",
    "method = raw",
    "raw_target = /dev/stdout",
    "data_format = ascii",
    "ascii_max_range = 100",
    "bar_delimiter = 59",
    "frame_delimiter = 10",
    "",
    "[smoothing]",
    "noise_reduction = 62",
    ""
  ]
  return lines.join("\n")
}
